### ISSUE TITLE
Re-add/re-implement offline mode

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/ansible-compat#137]
This was removed (because it apparently already didn't work correctly before that) in https://github.com/ansible/ansible-compat/pull/37

For more context see https://github.com/ansible/ansible-lint/issues/2042 - functionality in `ansible-lint` is currently broken/bugged due to this library automatically exec'ing out to `ansible-galaxy` whenever a certain file exists in the root folder of a repository.

**Comment by ssbarnea** [comment]
I agree that we need to bring back the offline mode in linter. The tricky question related to ansible-galaxy is should we assume that any install command requires online mode?

People could install archives from local disk, so it can become bit weird. Bug if we assume that `offline: true` skips any ansible-galaxy install call, it should not be hard to bring it back.

**Comment by nre-ableton** [comment]
@ssbarnea Thanks for the quick fix!

**Comment by ssbarnea** [comment]
That is not really fixed until we merge https://github.com/ansible/ansible-lint/pull/2115 but I need manual tests for that.

**Comment by nre-ableton** [comment]
Well, it's at least a step in the right direction. :smile:
