### ISSUE TITLE
molecule doesn't find role with ansible-compat == 1.0.0 (Regression)

### ISSUE THREAD

**Issue by niall-byrne** [ansible/ansible-compat#159]
Please see comments appended here: https://github.com/ansible/ansible-compat/issues/114

**Comment by zhan9san** [comment]
> https://github.com/osx-provisioner/role-symlinks/runs/7383794051?check_suite_focus=true#step:4:140

Could you please verify it in latest molecule?
`pip install molecule==4.0.0`
