### ISSUE TITLE
4.0.1 update broke molecule

### ISSUE THREAD

**Issue by luri-fr** [ansible/ansible-compat#260]
Hi,

As @john-bailey report yesterday here : https://github.com/ansible/ansible-compat/discussions/257
This update broke molecule.
We have to downgrade back to 3.0.2.

I have today the same issue of @john-bailey  and the same downgrade work.

I take this issue here because perhaps commentary is not the best place to report an issue.

Thanks for you're work

> FYI: This update broke Molecule, and I had to downgrade back to 3.0.2 Here's the traceback
> 
> ```
> Traceback (most recent call last):
>   File "/apps/ansible_test/.venv/bin/molecule", line 8, in <module>
>     sys.exit(main())
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/molecule/command/init/role.py", line 174, in role
>     r.execute()
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/molecule/command/init/role.py", line 84, in execute
>     result = util.run_command(cmd)
>   File "/apps/ansible_test/.venv/lib64/python3.9/site-packages/molecule/util.py", line 149, in run_command
>     result = app.runtime.exec(
> AttributeError: 'Runtime' object has no attribute 'exec'
> ```

**Comment by ssbarnea** [comment]
That is not a bug in ansible-compat, if you have installed `molecule[lock]`, you would not have reached this case, where a newer version of a dependency would break the tool.

There is nothing possible to fix on ansible-compat side, only on consumers, avoiding using incompatible version or switching to the new version.
