### ISSUE TITLE
Tag v4.1.12 is gone?

### ISSUE THREAD

**Issue by Antiz96** [ansible/ansible-compat#373]
Hello,

As one of the maintainer of the Ansible stack on Arch Linux's side, I noticed that the v4.1.12 tag has been deleted.

Apart from Debian, that still has the said tag in their [source's clone](https://salsa.debian.org/python-team/packages/python-ansible-compat/-/tags/upstream%2F4.1.12), [multiple distributions](https://repology.org/project/python:ansible-compat/versions) now have an `ansible-compat` package based on an non-existing upstream tag, preventing rebuilds and breaking reproducibility (until another *stable* tag is made at least).

Is there any specific reason for this deletion? If so, does some more tags removal should be expected in the future?

**Comment by ssbarnea** [comment]
@Antiz96 I removed it because the tag was never published on pypi and GHA config did not allow to retrigger the publish process. Let me see if I can publish it.

No expected tag removals.

**Comment by Antiz96** [comment]
> I pushed the tag back, should be identical.

Can confirm, thanks for you quick actions!
