### ISSUE TITLE
`lib64` symlinked to `lib` causes duplicate collection warnings

### ISSUE THREAD

**Issue by gardar** [ansible/ansible-compat#401]
In a `virtualenv` where `lib64` is a symlink to `lib`, I'm encountering repeated "Multiple versions" warnings for Ansible collections:

```
WARNING  Multiple versions of 'amazon.aws' were found installed, only the first one will be used...
```

This behavior appears to be related to this PR: [https://github.com/ansible/ansible-compat/pull/379](https://github.com/ansible/ansible-compat/pull/379)

**Steps to Reproduce:**

1. Create a `virtualenv`
2. Symlink `lib64` to `lib` within the `virtualenv`
3. Install Ansible
4. Run Ansible commands, `ansible-lint` for example.

**Expected Behavior:**

Ansible should not report duplicate collection warnings when `lib64` is symlinked to `lib`.

**Additional Information:**
```
ls -lah /opt/app-root/ | grep lib
drwxrwxr-x 1 default root 4.0K Aug 26 13:34 lib
lrwxrwxrwx 1 default root    3 Jun  5 12:03 lib64 -> lib
```

```
ls -lah /opt/app-root/lib/python3.12/site-packages/ansible_collections/
total 208K
drwxrwxr-x 50 default root 4.0K Aug 26 13:34 .
drwxrwxr-x  1 default root 4.0K Aug 26 13:34 ..
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 amazon
drwxrwxr-x  6 default root 4.0K Aug 26 13:34 ansible
-rw-rw-r--  1 default root  714 Aug 26 13:34 ansible_community.py
-rw-rw-r--  1 default root  200 Aug 26 13:34 ansible_release.py
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 arista
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 awx
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 azure
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 check_point
```

```
ls -lah /opt/app-root/lib64/python3.12/site-packages/ansible_collections/
total 208K
drwxrwxr-x 50 default root 4.0K Aug 26 13:34 .
drwxrwxr-x  1 default root 4.0K Aug 26 13:34 ..
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 amazon
drwxrwxr-x  6 default root 4.0K Aug 26 13:34 ansible
-rw-rw-r--  1 default root  714 Aug 26 13:34 ansible_community.py
-rw-rw-r--  1 default root  200 Aug 26 13:34 ansible_release.py
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 arista
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 awx
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 azure
drwxrwxr-x  3 default root 4.0K Aug 26 13:34 check_point
```

**Comment by xoxys** [comment]
Same here and it's pretty annoying as it is flooding the entire output if `ansible-community` is installed due to the amount of collections.

**Comment by ssbarnea** [comment]
Current versions this message no longer appears and in any case, this has nothing to do with venvs. Adding these symlinks to them seems like a recipe for breaking things.

**Comment by xoxys** [comment]
Thanks for just closing the issue... This symlink is added automatically on `venvs`, nothing was configured manually here just install Ansible in a venv and give it a try. However, as this seems to be the new working mode across the Ansible community, maybe it's time to switch to another config management system.
