### ISSUE TITLE
"molecule test" with the vagrant driver shows me a "role name" error even if I specify "role_name" and "namespace" on meta/main.yml

### ISSUE THREAD

**Issue by cejjebbouji** [ansible/ansible-compat#98]
To test my role locally, "molecule test" with the vagrant driver  fails by showing me:
Computed fully qualified role name of role.test does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:
galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

it keeps failing even if I add "role_name" and "namespace" on meta/main.yml.

I had to delete the three lines: 394, 395 and 396 on the file: "...../lib/python3.6/site-packages/ansible_compat/runtime.py" to prevent the error from occurring and so that I could run the test of my role.

**Comment by ssbarnea** [comment]
This should like be fixed by https://github.com/ansible/ansible-compat/releases/tag/v2.1.0 release
